# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: npm install
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd android && gradle clean build
        
          
